#!/usr/bin/env python
from livereload import Server, shell
server = Server()
server.watch('*.css')
server.watch('imgsrc/*', shell('make html'))
server.watch('*.md', shell('make html'))
server.serve()
